databases:
  - name: boat-cruise-reservation-api
    databaseName: boat_cruise_reservation_production
    user: boat_cruise_reservation
    plan: free

services:
  - type: web
    name: boat-cruise-reservation-api
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: boat-cruise-reservation-api
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default